export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_GOODS = 'GET_GOODS';
export const UPDATE_BASE = 'UPDATE_BASE';
export const UPDATE_SELECTED_GOODS = 'UPDATE_SELECTED_GOODS';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';